### ISSUE TITLE
Issue with vim-airline?

### ISSUE THREAD

**Issue by farzadmf** [yaronkh/vim-winmanip#1]
Hi,

There seems to be a conflict of some kind between this and vim-airline.

I open a file and whatever binding defined by this plugin I use, my neovim hangs, and I see a "million" of these messages:
```
E132: Function call depth is higher than 'maxfuncdepth'
Error detected while processing function <SNR>84_on_window_changed[23]..airline#update_statusline[6]..airline#update_statusline_inactive[15]..<SNR>105_invoke_funcrefs[4]..399[52]..<SNR>217_get_seperator[2]..<SNR>217_get_transition
ed_seperator[7]..airline#highlighter#add_separator[2]..<SNR>201_exec_separator[13]..airline#highlighter#exec[9]..airline#highlighter#get_highlight:
```

And then, when I press <kbd>q</kbd> to get out of those messages, I see my buffer bing split a "million" times, this is a screenshot of what it looks like:
![image](https://user-images.githubusercontent.com/5768792/107173075-f451a600-6994-11eb-9585-053251c34e36.png)

Seems like there's an infinite loop happening somewhere :thinking:

**Comment by yaronkh** [comment]
Thanks for reporting the problem, I will check it out

**Comment by yaronkh** [comment]
Hi, I am also using vim-airline with nvim and I have never faced this problem. 
Looking at the call stack that you sent to me, I don't find any call to winmanip.

I don't think that this problem is related to winmapin.
To get better understanding of the problem please provide the version of vim-airline that you use.
If you are using `vim-plug` plese run `:PlugSnapshot` and send me the the output.
I would also appreciate if you could send me your `init.vim` file.

YK

**Comment by farzadmf** [comment]
Hi @yaronkh , thank you for getting back to me.

If it doesn't happen for you, then maybe something else has a conflict or something to cause the issue. I'll try to install `winmanip` again and investigate.

As for my `init.vim`, I don't think that's feasible, because I have everything in a single file (personal preference :wink: ), and it's HUGE. I'll try to narrow down the problem to hopefully see what's causing the issue.

I'll get back to you with more info :slightly_smiling_face:

**Comment by yaronkh** [comment]
If I remember correctly I had the same problem and the problem was solved by upgrading vim-airline to the latest version

**Comment by farzadmf** [comment]
I'm not sure that will be the solution for me because I'm in the habit of updating my plugins very regularly.

However, I tried a minimal setup and the issue didn't happen, so it maybe something else messing things up, but finding it in my `vimrc` is even harder than finding a needle in a haystack :slightly_frowning_face:

**Comment by yaronkh** [comment]
Not a bug

**Comment by farzadmf** [comment]
@yaronkh true, will update if I find something "interesting"
